### ISSUE TITLE
Google maps could not get loaded

### ISSUE THREAD

**Issue by Primergz** [runette/ultima-ratio#84]
Google Maps cannot get loaded – it says:  Googe Maps couldnt loaded correctly on this Website. Technical Details are to be found in the JavaScript console“

I get this error both in Chrome and Firefox. Hadn’t any Problems with JavaScript on this page till now. 

![Google maps fehler](https://user-images.githubusercontent.com/55485543/74678229-b1faec00-51ba-11ea-9475-220d526d1132.jpg)

**Comment by runette** [comment]
Wrong URL

use www.bigcannonproject.org instead
